siteTitle = "Blog de Sochan"
siteDescr = "sochan's Tech blog"
siteAuthor = "sochan"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/"
